In [2]:
class STUDENT:
    def __init__(self):
        self.student_name = "Mohamed gamal"
        self.Student_age = 35
        self.student_grade = 3.99
        self.student_gender = "male"

    def student_info(self):
        print(f"My name is : {self.student_name}")
        print(f"My age is: {self.Student_age}") 
        print(f"My grade : {self.student_grade}")
        print(f"My gender : {self.student_gender}")

s1 = STUDENT()
s1.student_info()

My name is : Mohamed gamal
My age is: 35
My grade : 3.99
My gender : male


In [ ]:

#class Calculator take two numbers and perform addition and subtraction
# and print the results
class Calculator:
    def __init__(self, num1, num2):
        self.num1 = num1
        self.num2 = num2
    def add(self):
        return self.num1 + self.num2
    def subtract(self):
        return self.num1 - self.num2



num1 = int(input("Enter first number: "))   # Input first numbers from the user 
num2 = int(input("Enter second number: "))  # Input second numbers from the user 

c1 = Calculator(num1, num2)    # inherits the class Calculator
c1.add()                        # performs addition
c2 = Calculator(num1, num2)
c2.subtract()
print (f"Addition of {num1} and {num2} is: {c1.add()}")
print (f"Subtraction of {num1} and {num2} is: {c2.subtract()}")

Addition of 10 and 5 is: 15
Subtraction of 10 and 5 is: 5


In [1]:
from abc import ABC, abstractmethod

class Animal (ABC):
    @abstractmethod
    def move(self):
        pass

class Bird(Animal):
    def move(self):
        print("I can fly")

class Cat(Animal):
    def move(self):
        print("I can run")

a = Bird()
a.move()

I can fly


In [2]:
class A():
    def do_this(self):
        print("A is doing this")

class B(A):
    pass

class C():
    def do_this(self):
        print("C is doing this")

class D(B, C):
    pass

d = D()
x = d.do_this()

A is doing this


In [6]:
import random
class password_generator:
    def __init__(self, length):
        self.length = length

    def generate(self):
        characters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()"
        password = ""

        for _ in range(self.length):
            password += random.choice(characters)
        return password
    
if __name__ == "__main__":
    p1 = password_generator(10)  # Create an instance with desired length
    p1.generate()  # Generate the password
    print(f"Generated password: {p1.generate()}")  # Print the generated password





Generated password: vq(DP4WXdp


In [7]:
class WordFrequencyCounter:

    def __init__(self, words):
    
        self.words = words

    def count_frequencies(self):
    
        freq_dict = {}
        for word in self.words:
            if word in freq_dict:
                freq_dict[word] += 1
            else:
                freq_dict[word] = 1
        return freq_dict
if __name__ == "__main__":
    
    words = ["Welcome", "Ali", "Hi", "Ali", "No", "Hi", "No", "Ali", "No", "Ali"]
    
    counter = WordFrequencyCounter(words)
    result = counter.count_frequencies()

    for word, count in result.items():
        print(f"{word}: {count}")

Welcome: 1
Ali: 4
Hi: 2
No: 3


In [ ]:
def count_word_frequencies(words):
    freq_dict = {}
    for word in words:
        if word in freq_dict:
            freq_dict[word] += 1
        else:
            freq_dict[word] = 1
    return freq_dict

words = ["Welcome", "Ali", "Hi", "Ali", "No", "Hi", "No", "Ali", "No", "Ali"]
unique_words = set(words)
counts = {word: words.count(word) for word in unique_words}
for word in unique_words:
    print(f"{word}: {counts[word]}")




In [ ]:

def count_word_frequencies(words):

    freq_dict = {}
    for word in words:
        freq_dict[word] = freq_dict.get(word, 0) + 1
    return freq_dict

words = ["Welcome", "Ali", "Hi", "Ali", "No", "Hi", "No", "Ali", "No", "Ali"]

counts = count_word_frequencies(words)

for word in sorted(counts):
    print(f"{word}: {counts[word]}")

In [ ]:
class WordFrequencies:
    def __init__(self, words):
        self.words = words

    def count_word_frequencies(self):
        freq_dict = {}
        for word in self.words:
            freq_dict[word] = freq_dict.get(word, 0) + 1
        return freq_dict

    def display_frequencies(self):
        counts = self.count_word_frequencies()
        for word in sorted(counts):
            print(f"{word}: {counts[word]}")

if __name__ == "__main__":
    words = ["Welcome", "Ali", "Hi", "Ali", "No", "Hi", "No", "Ali", "No", "Ali"]
    wf = WordFrequencies(words)
    wf.display_frequencies()


In [ ]:
import random

# Predefined responses
responses = {
    "hello": ["Hello!", "Hi there!", "Greetings!"],
    "how are you": ["I'm doing well, thank you!", "I'm fine, how about you?"],
    "goodbye": ["Goodbye!", "See you later!", "Farewell!"],
    "default": ["I'm sorry, I didn't understand.", "Could you please rephrase that?"]
}

# Function to get a response based on user input
def get_response(user_input):
    for key in responses:
        if key in user_input:
            return random.choice(responses[key])
    
    return random.choice(responses["default"])

# Chatbot function
def chatbot():
    print("Chatbot: Hi! How can I assist you today?")
    
    while True:
        user_input = input("User: ").lower()
        response = get_response(user_input)
        print("Chatbot:", response)
        
        if user_input == "goodbye":
            break

# Run the chatbot
chatbot()

In [12]:
import random

class ChatBot:
    def __init__(self):
        self.responses = {
            "hello": ["Hello!", "Hi there!", "Greetings!"],
            "how are you": ["I'm good, thanks!", "Doing well, and you?"],
            "goodbye": ["Goodbye!", "See you!", "Take care!"],
            "default": ["I didn't get that.", "Could you repeat it?"]
        }

    def get_response(self, user_input):
        user_input = user_input.lower()
        for key in self.responses:
            if key in user_input:
                return random.choice(self.responses[key])
        return random.choice(self.responses["default"])

    def start(self):
        print("Chatbot: Hello! Type 'goodbye' to exit.")
        while True:
            user_input = input("You: ")
            response = self.get_response(user_input)
            print("Chatbot:", response)
            if "goodbye" in user_input.lower():
                break


bot = ChatBot()
bot.start()


Chatbot: Hello! Type 'goodbye' to exit.
Chatbot: Hi there!
Chatbot: Could you repeat it?
Chatbot: I'm good, thanks!
Chatbot: Could you repeat it?
Chatbot: Goodbye!


In [3]:
import numpy as np

# Example usage of numpy
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(v1)
print(v2)


[1 2 3]
[4 5 6]


In [ ]:
list_1 = [1, 2, 3] 
print(type(list_1)) # check type of list_1
# Convert list_1 to a numpy array
x = np.array(list_1) 
print(type(x))

<class 'list'>
<class 'numpy.ndarray'>


In [6]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
w= v1 * v2  # Add two numpy arrays
print(w)  # Print the result of the addition


[ 4 10 18]


In [1]:
import numpy as np

In [7]:
s= np.array(5)  # Create a numpy array with a single element
print (type(s))  # Check the type of the numpy array
print("D", s.ndim)  # Print the number of dimensions
print(s)  # Print the numpy array

<class 'numpy.ndarray'>
D 0
5


In [9]:
v= np.array([1, 2, 3])
print(type(v))  # Check the type of the numpy array
print(v.shape)  # Print the shape of the numpy array
v

<class 'numpy.ndarray'>
(3,)


array([1, 2, 3])

In [11]:
m= np.array([[1, 2, 3],
            [4, 5, 6]
            ])
print(type(m))  # Check the type of the numpy array
print(m.ndim , "D")  # Print the number of dimensions
print(m.shape)  # Print the shape of the numpy array
print(m)  # Print the numpy array

<class 'numpy.ndarray'>
2 D
(2, 3)
[[1 2 3]
 [4 5 6]]


In [12]:
vec_1 = np.array([1, 2, 3, 4 ,5 , 6])  
matrix_1 = vec_1.reshape(3,2)  # Reshape the vector into a 2x3 matrix
print(matrix_1)  # Print the reshaped matrix
print(type(matrix_1))  # Check the type of the reshaped matrix

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>


In [17]:
vec_2 = np.array([1, 2, 3, 4 ,5 ])
matrix_3 = vec_2.reshape(vec_2.shape[0],1)  
print(matrix_3)  

[[1]
 [2]
 [3]
 [4]
 [5]]


In [18]:
vec_2 = np.array([1, 2, 3, 4 ,5 ])
#matrix_3 = vec_2.reshape(vec_2.shape[0],1)  
matrix_4 = vec_2[:, None]  # Reshape the vector into a column vector
print(matrix_4) 

[[1]
 [2]
 [3]
 [4]
 [5]]


In [19]:
m_1 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7,8,9]
                ])

print(m_1.dtype)  # Check the type of the numpy array

int64


In [20]:
m_1 = np.array([[1, True, 3],
                [4, 5, 6],
                [7,8,9]
                ])

print(m_1.dtype)  # Check the type of the numpy array

int64


In [27]:
class student:
    def __init__(self, name):
        self.name = name

s = student("Mohamed Gamal")
m_1 = np.array([[1, True, s.name],
                [4, 5, 6],
                [7,8,9]
                ])

print(m_1.dtype) 
print(m_1)  # Print the numpy array with mixed data types


<U21
[['1' 'True' 'Mohamed Gamal']
 ['4' '5' '6']
 ['7' '8' '9']]


In [ ]:
m = np.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [0,0,0]
        ])  # indexing example [1 ,2 , 3] = index 0 

m[1,2]

np.int64(6)

In [31]:
m = np.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [0,0,0]
        ])  # indexing example [1 ,2 , 3] = index 0 

m[1,-2]

np.int64(5)

In [33]:
v_3 = np.array([3,2,5,1,2,3,0])
v_3[2:6]  # Slicing the array to get elements from index 2 to 4

array([5, 1, 2, 3])

In [34]:
m = np.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [0,0,0]
        ])

m[1:3 , 0:2]  # Slicing the array to get rows 1 to 2 and columns 0 to 1

array([[4, 5],
       [7, 8]])

In [35]:
m = np.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [0,0,0]
        ])

m[-3:-1 , -3:-1]  # Slicing the array to get rows 1 to 2 and columns 0 to 1

array([[4, 5],
       [7, 8]])

In [36]:
m = np.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [0,0,0]
        ])

mat_t = m.T  # Transpose the matrix
print(mat_t)  # Print the transposed matrix

[[1 4 7 0]
 [2 5 8 0]
 [3 6 9 0]]


In [38]:
mat = np.zeros((3, 4))  # Create a 2x3 matrix filled with zeros
mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
mat = np.ones((3, 4))  # Create a 2x3 matrix filled with zeros
mat

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
mat = np.full((3, 4), 5)  # Create a 3*4 matrix filled with fives
print(mat)  # Print the matrix filled with fives

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [44]:
mat = np.empty((3, 4))  # Create an empty matrix with shape 3x4
print(mat)  # Print the empty matrix

[[2.5e-323 2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323 2.5e-323]]


In [47]:
angles = np.arange(0,361,30)  # Create a numpy array with angles
print(angles)  # Print the numpy array with angles

[  0  30  60  90 120 150 180 210 240 270 300 330 360]


In [51]:
vec = np.linspace(0, 10, num = 10)  # Create a numpy array with evenly spaced values
print(vec)  # Print the numpy array with evenly spaced values

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [53]:
iden = np. identity(3,)      # Create a 3x3 identity matrix
print(iden)  # Print the identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [57]:
vec = np.linspace(0, 10, num = 25)  # Create a numpy array with evenly spaced values
mat = vec.reshape(5, 5)  # Reshape the vector into a 5x5 matrix
print(mat)  # Print the numpy array with evenly spaced values

[[ 0.          0.41666667  0.83333333  1.25        1.66666667]
 [ 2.08333333  2.5         2.91666667  3.33333333  3.75      ]
 [ 4.16666667  4.58333333  5.          5.41666667  5.83333333]
 [ 6.25        6.66666667  7.08333333  7.5         7.91666667]
 [ 8.33333333  8.75        9.16666667  9.58333333 10.        ]]


In [60]:
np. random.random((3, 4))  # Create a 3x4 matrix with random values
print(np.random.random((3, 4)))  # Print the random matrix

[[0.79186594 0.65402678 0.44168126 0.31160391]
 [0.04822086 0.21036576 0.6148988  0.78342293]
 [0.57749712 0.34201432 0.61421345 0.98859533]]


In [1]:
import numpy as np

In [ ]:
mat_1 = np.ones((3, 4))  # Create a 3x4 matrix filled with ones
print(mat_1)  # Print the matrix filled with ones   
mat_2 = np.zeros((4, 4))  # Create another 3x4 matrix filled with ones
print(mat_2)  # Print the second matrix filled with ones

np.savez("C:/Users/Mgama/Ai_Amit_Diploma/images.npz" , ones_mat = mat_1 , zeros_mat = mat_2)  # Save the matrices to a .npz file

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
with np.load("C:/Users/Mgama/Ai_Amit_Diploma/images.npz") as file:  # Load the saved matrices from the .npz file
    mat_1 = file['ones_mat']  # Access the matrix filled with ones
    mat_2 = file['zeros_mat']  # Access the matrix filled with zeros
    print(mat_1)  # Print the loaded matrix filled with ones
    print(mat_2)  # Print the loaded matrix filled with zeros

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [9]:
m_1 = np.array([[1, 2, 3],
                [0, 0, 0]])
m_2 = np.array([[4, 5, 6],
                [1, 1, 1]])

v_mat = np.vstack((m_1, m_2))  # Stack the two matrices vertically
print(v_mat)  # Print the vertically stacked matrix

[[1 2 3]
 [0 0 0]
 [4 5 6]
 [1 1 1]]


In [10]:
m_1 = np.array([[1, 2, 3],
                [0, 0, 0]])
m_2 = np.array([[4, 5, 6],
                [1, 1, 1]])

v_mat = np.hstack((m_1, m_2))  # Stack the two matrices vertically
print(v_mat)  # Print the vertically stacked matrix

[[1 2 3 4 5 6]
 [0 0 0 1 1 1]]


In [11]:
s = 4
v= np.array([1, 2, 3, 4, 5])  # Create a numpy array with values from 1 to 5
v == s  # Check if the elements of the array are equal to 4

array([False, False, False,  True, False])

In [13]:
v1 = np.array([1, 3, 3])
v2 = np.array([4, 3, 4])
v1 == v2  # Check if the two arrays are equal element-wise

array([False,  True, False])

In [14]:
m_1 = np.array([[1, 2, 3],
                [0, 0, 0]])
m_2 = np.array([[4, 2, 6],
                [1, 0, 1]])
m_1 == m_2  # Check if the two matrices are equal element-wise

array([[False,  True, False],
       [False,  True, False]])

In [15]:
v = np.array([1, 2, 3, 4, 5])
np.all(v>1)  # Check if all elements of the array are greater than 1


np.False_

In [16]:
v = np.array([1, 2, 3, 4, 5])
np.any(v>1)  # Check if any elements of the array are greater than 1

np.True_

In [18]:
v1 = np.array([1, 2, 1 ,4, 5])
v2 = np.array([2, 4, 0 ,6, 3])
np.isclose(v1, v2 , atol= 1)  # Check if the two arrays are close to each other element-wise

array([ True, False,  True, False, False])

In [25]:
v1 = np.array([1, 2, 1 ,1, 1])
v2 = np.array([1, 1, 1 ,1, 1])
np.allclose(v1, v2 , atol= 1)  # Check if the two arrays are close to each other element-wise

True

In [26]:
v = np.array([1, 2, 3, 4, 5])
condition = v >= 4
print(condition)  # Print the boolean array where elements are greater than or equal to 4

[False False False  True  True]


In [28]:
v = np.array([1, 2, 3, 4, 5])
condition = v >= 4
print (condition)  # Print the boolean array where elements are greater than or equal to 4
condition_access = v[condition]  # Access the elements of the array that satisfy the condition
print(condition_access)  # Print the elements of the array that satisfy the condition

[False False False  True  True]
[4 5]


In [29]:
v = np.array([1, 2, 3, 4, 5])
condition = v >= 4
print (condition)  # Print the boolean array where elements are greater than or equal to 4
v[condition]  = -1 # 
print (v)  # Print the modified array where elements greater than or equal to 4 are set to -1

[False False False  True  True]
[ 1  2  3 -1 -1]


In [30]:
v = np.array([1, 2, 3, 4, 5])
condition = v >= 4
n_condition = np.where(condition, -1, v)  # Set elements greater than or equal to 4 to -1
print(n_condition)  # Print the modified array where elements greater than or equal to 4

[ 1  2  3 -1 -1]


In [1]:
pip install pandas # Install pandas library

Note: you may need to restart the kernel to use updated packages.


ERROR: Invalid requirement: '#': Expected package name at the start of dependency specifier
    #
    ^


In [1]:
import pandas as pd  # Import pandas library


In [6]:
s = pd.Series([1, 2, 3, 4])  # Create a pandas Series with values from 1 to 5

print(s)  # Print the pandas Series

0    1
1    2
2    3
3    4
dtype: int64


In [7]:
s = pd.Series([1, 2, 3, 4], index=["A","b", "c","D"]) # create a pandas Series with custom index
print(s)  # Print the pandas Series with custom index

A    1
b    2
c    3
D    4
dtype: int64


In [10]:
data_1 = [[1,111,'Ahmed'],
            [2,222,'Ali'],
            [3,333,'Mohamed'],
            [4,444,'Gamal']
            ]

type(data_1)  # Check the type of data_1, which should be a list of lists
df = pd.DataFrame(data_1, columns=["Index", "ID", "Name"])  # Create a pandas DataFrame from the list of lists
print(df)  # Print the pandas DataFrame

   Index   ID     Name
0      1  111    Ahmed
1      2  222      Ali
2      3  333  Mohamed
3      4  444    Gamal


In [11]:
data_2 ={"s1" : [10 ,11, 17, 9],
            "s2" : [10 ,12, 15, 10],
            "s3" : ['math', 'science', 'english', "arabic"]}
df2 = pd.DataFrame(data_2)  # Create a pandas DataFrame from the dictionary
print(df2)  # Print the pandas DataFrame created from the dictionary

   s1  s2       s3
0  10  10     math
1  11  12  science
2  17  15  english
3   9  10   arabic


In [12]:
display(df2)  # Display the DataFrame in a Jupyter Notebook or similar environment

s1  s2       s3
0  10  10     math
1  11  12  science
2  17  15  english
3   9  10   arabic

In [ ]:
class name :
    def __init__(self, name: str):
        self.name = name

    @property
    def info(self):
        """Return the name of the instance."""
        return self.name  # Return the name of the instance

In [14]:
name = name("Mohamed Gamal")  # Create an instance of the class with a name
print(name.info)  # Print the name of the instance using the info property

Mohamed Gamal


In [15]:
data_1 = [[1,111,'Ahmed'],
            [2,222,'Ali'],
            [3,333,'Mohamed'],
            [4,444,'Gamal']
            ]

df = pd.DataFrame(data_1, columns=["Index", "ID", "Name"])  # Create a pandas DataFrame from the list of lists
df["ID"]

0    111
1    222
2    333
3    444
Name: ID, dtype: int64

In [18]:
data_1 = [[1,111,'Ahmed'],
            [2,222,'Ali'],
            [3,333,'Mohamed'],
            [4,444,'Gamal']
            ]

df = pd.DataFrame(data_1, columns=["Index", "ID", "Name"])  # Create a pandas DataFrame from the list of lists
df['Name'] = df['Name'].astype("category")  # Convert the 'Name' column to cataegory type
df.dtypes

Index       int64
ID          int64
Name     category
dtype: object

In [19]:
# EDA Exploratory data analysis
df.head()  # Display the first few rows of the DataFrame

Index   ID     Name
0      1  111    Ahmed
1      2  222      Ali
2      3  333  Mohamed
3      4  444    Gamal

In [20]:
df.tail(1)  # Display the last few rows of the DataFrame 

Index   ID   Name
3      4  444  Gamal

In [22]:
df.describe()  # Display summary statistics of the DataFrame

Index          ID
count  4.000000    4.000000
mean   2.500000  277.500000
std    1.290994  143.300384
min    1.000000  111.000000
25%    1.750000  194.250000
50%    2.500000  277.500000
75%    3.250000  360.750000
max    4.000000  444.000000

In [ ]:
df.describe(include='category')  # Display summary statistics of the DataFrame including all data types

Name
count       4
unique      4
top     Ahmed
freq        1

In [24]:
df.columns  # Display the columns of the DataFrame

Index(['Index', 'ID', 'Name'], dtype='object')

In [25]:
df['Name'].unique()  # Display unique values in the 'Name' column

['Ahmed', 'Ali', 'Mohamed', 'Gamal']
Categories (4, object): ['Ahmed', 'Ali', 'Gamal', 'Mohamed']

In [26]:
df['ID'].max()  # Display the maximum value in the 'ID' column

np.int64(444)

In [27]:
df['ID'].min()  # Display the min value in the 'ID' column

np.int64(111)

In [28]:
df['ID'].idxmin()

0

In [29]:
df.info()  # Display information about the DataFrame including data types and non-null counts

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype   
---  ------  --------------  -----   
 0   Index   4 non-null      int64   
 1   ID      4 non-null      int64   
 2   Name    4 non-null      category
dtypes: category(1), int64(2)
memory usage: 404.0 bytes


In [31]:
d = df["ID"].value_counts()  # Count the occurrences of each value in the 'ID' column
d  # Display the value counts of the 'ID' column

ID
111    1
222    1
333    1
444    1
Name: count, dtype: int64

In [32]:
d = df["ID"].sum()  # sum the values in the 'ID' column
d  # Display the value counts of the 'ID' column

np.int64(1110)

In [33]:
df.values  # Display the values of the DataFrame

array([[1, 111, 'Ahmed'],
       [2, 222, 'Ali'],
       [3, 333, 'Mohamed'],
       [4, 444, 'Gamal']], dtype=object)

In [34]:
df.replace(111, 'Jimmy')  # Replace the value 111 with 'Jimmy' in the DataFrame

Index     ID     Name
0      1  Jimmy    Ahmed
1      2    222      Ali
2      3    333  Mohamed
3      4    444    Gamal

In [35]:
df.replace({333:"Youssef" , 444 : "Ahmed"})  # Replace multiple values in the DataFrame

Index       ID     Name
0      1      111    Ahmed
1      2      222      Ali
2      3  Youssef  Mohamed
3      4    Ahmed    Gamal

In [36]:
df

Index   ID     Name
0      1  111    Ahmed
1      2  222      Ali
2      3  333  Mohamed
3      4  444    Gamal

In [40]:
def duplicate(x):
    """Function to duplicate a value."""
    return x * 2  # Return the duplicated value
df['Index'].apply(duplicate)  # Apply the duplicate function to the 'ID' column

0    2
1    4
2    6
3    8
Name: Index, dtype: int64

In [41]:
def duplicate(x):
    """Function to duplicate a value."""
    return x * 2  # Return the duplicated value
df['Index'].apply(lambda x :x*2)  # Apply a lambda function to duplicate the values in the 'ID' column

0    2
1    4
2    6
3    8
Name: Index, dtype: int64

In [43]:
df.ID.iloc[0]  # Access the first element of the 'ID' column using iloc

np.int64(222)

In [44]:
df

Index   ID     Name
0      1  222    Ahmed
1      2  444      Ali
2      3  666  Mohamed
3      4  888    Gamal

In [50]:
df.iloc[:,0:3]  # Access the first element of the 'ID' column using iloc 

Index   ID     Name
0      1  222    Ahmed
1      2  444      Ali
2      3  666  Mohamed
3      4  888    Gamal

In [55]:
T = df.iloc[:,0:2]  # Access the first column of the DataFrame using iloc
O = df.iloc[:,2:3]  # Access the second column of the DataFrame using iloc
print(T)  # Print the first column of the DataFrame
print(O)  # Print the second column of the DataFrame

   Index   ID
0      1  222
1      2  444
2      3  666
3      4  888
      Name
0    Ahmed
1      Ali
2  Mohamed
3    Gamal


In [60]:
data_1 = [[1,111,'Ahmed'],
            [2,222,'Ali'],
            [3,333,'Mohamed'],
            [4,444,'Gamal']
            ]

df = pd.DataFrame(data_1, columns=["Index", "ID", "Name"])  # Create a pandas DataFrame from the list of lists
df['Name'] = df['Name'].astype("category")  # Convert the 'Name' column to cataegory type
new_co = df.Index + df.ID
new_co  # Display the new column created by assigning 'ID' to 'Index'

0    112
1    224
2    336
3    448
dtype: int64

In [62]:
data_1 = [[1,111,'Ahmed'],
            [2,222,'Ali'],
            [3,333,'Mohamed'],
            [4,444,'Gamal']
            ]

df = pd.DataFrame(data_1, columns=["Index", "ID", "Name"])  # Create a pandas DataFrame from the list of lists
df['Name'] = df['Name'].astype("category")  # Convert the 'Name' column to cataegory type
df

Index   ID     Name
0      1  111    Ahmed
1      2  222      Ali
2      3  333  Mohamed
3      4  444    Gamal

In [65]:
new_co = df.Index + df.ID  # Create a new column by adding 'Index' and 'ID'
new_co  # Display the new column created by assigning 'ID' to 'Index'

0    112
1    224
2    336
3    448
dtype: int64

In [66]:
df.insert(3, "New_Column", new_co)  # Insert the new column into the DataFrame at index 3
df  # Display the DataFrame with the new column inserted

Index   ID     Name  New_Column
0      1  111    Ahmed         112
1      2  222      Ali         224
2      3  333  Mohamed         336
3      4  444    Gamal         448

In [69]:
df.drop("New_Column", axis=1 , inplace= True)  # Drop the 'new_co' column from the DataFrame
df  # Display the DataFrame after dropping the 'new_co' column

Index   ID     Name
0      1  111    Ahmed
1      2  222      Ali
2      3  333  Mohamed
3      4  444    Gamal

In [71]:
#to read table from linke or you can put the path of your own tabl
data=pd.read_table('http://bit.ly/movieusers')
data.head()  # Display the first few rows of the DataFrame read from the link

1|24|M|technician|85711
0       2|53|F|other|94043
1      3|23|M|writer|32067
2  4|24|M|technician|43537
3       5|33|F|other|15213
4   6|42|M|executive|98101

In [ ]:
data=pd.read_table('http://bit.ly/movieusers', sep='|')  # Read the table from the link with a comma as the separator
data  # Display the first few rows of the DataFrame read from the link

1  24  M     technician  85711
0      2  53  F          other  94043
1      3  23  M         writer  32067
2      4  24  M     technician  43537
3      5  33  F          other  15213
4      6  42  M      executive  98101
..   ...  .. ..            ...    ...
937  939  26  F        student  33319
938  940  32  M  administrator  02215
939  941  20  M        student  97229
940  942  48  F      librarian  78209
941  943  22  M        student  77841

[942 rows x 5 columns]

In [73]:
data=pd.read_table('http://bit.ly/movieusers', sep='|', header= None)  # Read the table from the link with a comma as the separator
data.head()  # Display the first few rows of the DataFrame read from the link

0   1  2           3      4
0  1  24  M  technician  85711
1  2  53  F       other  94043
2  3  23  M      writer  32067
3  4  24  M  technician  43537
4  5  33  F       other  15213

In [4]:
header_colums = ['Index' , 'age', 'gander', 'dept', 'Id']
data=pd.read_table('http://bit.ly/movieusers', sep='|', header= None , names=  header_colums)  # Read the table from the link with a comma as the separator
data.head()  # Display the first few rows of the DataFrame read from the link

Index  age gander        dept     Id
0      1   24      M  technician  85711
1      2   53      F       other  94043
2      3   23      M      writer  32067
3      4   24      M  technician  43537
4      5   33      F       other  15213

In [8]:
user_info=pd.read_csv('http://bit.ly/uforeports')
user_info.head(10)  # Display the first few rows of the DataFrame read from the link

City Colors Reported Shape Reported State              Time
0                Ithaca             NaN       TRIANGLE    NY    6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ   6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO   2/15/1931 14:00
3               Abilene             NaN           DISK    KS    6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY   4/18/1933 19:00
5           Valley City             NaN           DISK    ND   9/15/1934 15:30
6           Crater Lake             NaN         CIRCLE    CA    6/15/1935 0:00
7                  Alma             NaN           DISK    MI    7/15/1936 0:00
8               Eklutna             NaN          CIGAR    AK  10/15/1936 17:00
9               Hubbard             NaN       CYLINDER    OR    6/15/1937 0:00

In [78]:
user_info.City.head(10)  # Display the first few rows of the 'City' column in the DataFrame

0                  Ithaca
1             Willingboro
2                 Holyoke
3                 Abilene
4    New York Worlds Fair
5             Valley City
6             Crater Lake
7                    Alma
8                 Eklutna
9                 Hubbard
Name: City, dtype: object

In [81]:
user_info['Colors Reported'].head()  # Display the first few rows of the 'Colors Reportedcolors' column in the DataFrame

0    NaN
1    NaN
2    NaN
3    NaN
4    NaN
Name: Colors Reported, dtype: object

In [ ]:
user_info.shape  # Display the shape of the DataFrame

(18241, 5)

In [91]:
user_info.City + ' ' + user_info.State


0                      Ithaca NY
1                 Willingboro NJ
2                     Holyoke CO
3                     Abilene KS
4        New York Worlds Fair NY
                  ...           
18236              Grant Park IL
18237             Spirit Lake IA
18238             Eagle River WI
18239             Eagle River WI
18240                    Ybor FL
Length: 18241, dtype: object

In [9]:
user_info['location'] = user_info.City + ' ' + user_info.State
user_info.head()  # Display the first few rows of the DataFrame with the new 'location' column

City Colors Reported Shape Reported State             Time  \
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00   
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00   
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00   
3               Abilene             NaN           DISK    KS   6/1/1931 13:00   
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00   

                  location  
0                Ithaca NY  
1           Willingboro NJ  
2               Holyoke CO  
3               Abilene KS  
4  New York Worlds Fair NY

In [10]:
user_info.to_csv("new_data.csv") # Save the DataFrame to a CSV file named "new_data.csv"

In [4]:
new_file = pd.read_csv("new_data.csv")  # Read the newly created CSV file
new_file.head()  # Display the first few rows of the newly created CSV file

Unnamed: 0                  City Colors Reported Shape Reported State  \
0           0                Ithaca             NaN       TRIANGLE    NY   
1           1           Willingboro             NaN          OTHER    NJ   
2           2               Holyoke             NaN           OVAL    CO   
3           3               Abilene             NaN           DISK    KS   
4           4  New York Worlds Fair             NaN          LIGHT    NY   

              Time                 location  
0   6/1/1930 22:00                Ithaca NY  
1  6/30/1930 20:00           Willingboro NJ  
2  2/15/1931 14:00               Holyoke CO  
3   6/1/1931 13:00               Abilene KS  
4  4/18/1933 19:00  New York Worlds Fair NY

In [6]:
new_file.head(20)  # Display the first 20 rows of the newly created CSV file
new_file.tail(20)  # Display the last 20 rows of the newly created CSV

Unnamed: 0            City Colors Reported Shape Reported State  \
18221       18221        Franklin             NaN           DISK    NH   
18222       18222  Albrightsville             NaN          OTHER    PA   
18223       18223      Greenville             NaN            NaN    SC   
18224       18224         Eufaula             NaN           DISK    OK   
18225       18225     Simi Valley             NaN      FORMATION    CA   
18226       18226   San Francisco             NaN      FORMATION    CA   
18227       18227   San Francisco             NaN       TRIANGLE    CA   
18228       18228      Kingsville             NaN          LIGHT    TX   
18229       18229         Chicago             NaN           DISK    IL   
18230       18230     Pismo Beach             NaN           OVAL    CA   
18231       18231     Pismo Beach             NaN           OVAL    CA   
18232       18232            Lodi             NaN            NaN    WI   
18233       18233       Anchorage             RED        VARIOUS    AK   
18234       18234        Capitola             NaN       TRIANGLE    CA   
18235       18235  Fountain Hills             NaN            NaN    AZ   
18236       18236      Grant Park             NaN       TRIANGLE    IL   
18237       18237     Spirit Lake             NaN           DISK    IA   
18238       18238     Eagle River             NaN            NaN    WI   
18239       18239     Eagle River             RED          LIGHT    WI   
18240       18240            Ybor             NaN           OVAL    FL   

                   Time           location  
18221  12/29/2000 20:50        Franklin NH  
18222  12/29/2000 21:00  Albrightsville PA  
18223  12/29/2000 22:00      Greenville SC  
18224  12/29/2000 23:30         Eufaula OK  
18225  12/30/2000 10:00     Simi Valley CA  
18226  12/30/2000 22:00   San Francisco CA  
18227  12/30/2000 22:00   San Francisco CA  
18228   12/31/2000 4:00      Kingsville TX  
18229  12/31/2000 11:45         Chicago IL  
18230  12/31/2000 20:00     Pismo Beach CA  
18231  12/31/2000 20:00     Pismo Beach CA  
18232  12/31/2000 20:30            Lodi WI  
18233  12/31/2000 21:00       Anchorage AK  
18234  12/31/2000 22:00        Capitola CA  
18235  12/31/2000 23:00  Fountain Hills AZ  
18236  12/31/2000 23:00      Grant Park IL  
18237  12/31/2000 23:00     Spirit Lake IA  
18238  12/31/2000 23:45     Eagle River WI  
18239  12/31/2000 23:45     Eagle River WI  
18240  12/31/2000 23:59            Ybor FL

In [5]:
new_file.tail()  # Display the last row of the newly created CSV file

Unnamed: 0         City Colors Reported Shape Reported State  \
18236       18236   Grant Park             NaN       TRIANGLE    IL   
18237       18237  Spirit Lake             NaN           DISK    IA   
18238       18238  Eagle River             NaN            NaN    WI   
18239       18239  Eagle River             RED          LIGHT    WI   
18240       18240         Ybor             NaN           OVAL    FL   

                   Time        location  
18236  12/31/2000 23:00   Grant Park IL  
18237  12/31/2000 23:00  Spirit Lake IA  
18238  12/31/2000 23:45  Eagle River WI  
18239  12/31/2000 23:45  Eagle River WI  
18240  12/31/2000 23:59         Ybor FL

In [7]:
new_file.describe()

Unnamed: 0
count  18241.000000
mean    9120.000000
std     5265.867466
min        0.000000
25%     4560.000000
50%     9120.000000
75%    13680.000000
max    18240.000000

In [8]:
new_file.describe(include= 'object')

City Colors Reported Shape Reported  State              Time  \
count     18215            2882          15597  18241             18241   
unique     6475              27             27     52             16145   
top     Seattle             RED          LIGHT     CA  11/16/1999 19:00   
freq        187             780           2803   2529                27   

          location  
count        18215  
unique        8028  
top     Seattle WA  
freq           187

In [9]:
new_file [0:10] # Display the first 10 rows of the newly created CSV file

Unnamed: 0                  City Colors Reported Shape Reported State  \
0           0                Ithaca             NaN       TRIANGLE    NY   
1           1           Willingboro             NaN          OTHER    NJ   
2           2               Holyoke             NaN           OVAL    CO   
3           3               Abilene             NaN           DISK    KS   
4           4  New York Worlds Fair             NaN          LIGHT    NY   
5           5           Valley City             NaN           DISK    ND   
6           6           Crater Lake             NaN         CIRCLE    CA   
7           7                  Alma             NaN           DISK    MI   
8           8               Eklutna             NaN          CIGAR    AK   
9           9               Hubbard             NaN       CYLINDER    OR   

               Time                 location  
0    6/1/1930 22:00                Ithaca NY  
1   6/30/1930 20:00           Willingboro NJ  
2   2/15/1931 14:00               Holyoke CO  
3    6/1/1931 13:00               Abilene KS  
4   4/18/1933 19:00  New York Worlds Fair NY  
5   9/15/1934 15:30           Valley City ND  
6    6/15/1935 0:00           Crater Lake CA  
7    7/15/1936 0:00                  Alma MI  
8  10/15/1936 17:00               Eklutna AK  
9    6/15/1937 0:00               Hubbard OR

In [10]:
new_file . columns  # Display the columns of the newly created CSV file

Index(['Unnamed: 0', 'City', 'Colors Reported', 'Shape Reported', 'State',
       'Time', 'location'],
      dtype='object')

In [11]:
new_file.info()  # Display information about the newly created CSV file including data types and non-null counts

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18241 entries, 0 to 18240
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Unnamed: 0       18241 non-null  int64 
 1   City             18215 non-null  object
 2   Colors Reported  2882 non-null   object
 3   Shape Reported   15597 non-null  object
 4   State            18241 non-null  object
 5   Time             18241 non-null  object
 6   location         18215 non-null  object
dtypes: int64(1), object(6)
memory usage: 997.7+ KB


In [12]:
new_file .head(2)  # Display the first few rows of the newly created CSV file

Unnamed: 0         City Colors Reported Shape Reported State  \
0           0       Ithaca             NaN       TRIANGLE    NY   
1           1  Willingboro             NaN          OTHER    NJ   

              Time        location  
0   6/1/1930 22:00       Ithaca NY  
1  6/30/1930 20:00  Willingboro NJ

In [18]:
new_file.rename(columns ={'Colors Reported':'Colors_Reported', 'Shape Reported':'Shape_Reported'} , inplace = True)  # Rename the 'Colors Reported' column to 'col' in the newly created CSV file
new_file.head()  # Display the first few rows of the newly created CSV file

Unnamed: 0                  City Colors_Reported Shape_Reported State  \
0           0                Ithaca             NaN       TRIANGLE    NY   
1           1           Willingboro             NaN          OTHER    NJ   
2           2               Holyoke             NaN           OVAL    CO   
3           3               Abilene             NaN           DISK    KS   
4           4  New York Worlds Fair             NaN          LIGHT    NY   

              Time                 location  
0   6/1/1930 22:00                Ithaca NY  
1  6/30/1930 20:00           Willingboro NJ  
2  2/15/1931 14:00               Holyoke CO  
3   6/1/1931 13:00               Abilene KS  
4  4/18/1933 19:00  New York Worlds Fair NY

In [22]:
new_file.columns = new_file.columns.str.replace(' ', '_')  # Replace spaces in column names with underscores
new_file.head(2)  # Display the first few rows of the newly created CSV file with updated column names

Unnamed:_0         City Colors_Reported Shape_Reported State  \
0           0       Ithaca             NaN       TRIANGLE    NY   
1           1  Willingboro             NaN          OTHER    NJ   

              Time        location  
0   6/1/1930 22:00       Ithaca NY  
1  6/30/1930 20:00  Willingboro NJ

In [23]:
new_file.drop(['Colors_Reported' , 'City'] , axis=1 , inplace=True)  # Drop the 'Colors Reported' and 'City' columns from the newly created CSV file
new_file.head(2)  # Display the first few rows of the newly created CSV file with updated column names

Unnamed:_0 Shape_Reported State             Time        location
0           0       TRIANGLE    NY   6/1/1930 22:00       Ithaca NY
1           1          OTHER    NJ  6/30/1930 20:00  Willingboro NJ

In [24]:
new_file.drop([0,1,2], axis=0, inplace=True)  # Drop the first three rows from the newly created CSV file
new_file.head(2)  # Display the first few rows of the newly created CSV file

Unnamed:_0 Shape_Reported State             Time                 location
3           3           DISK    KS   6/1/1931 13:00               Abilene KS
4           4          LIGHT    NY  4/18/1933 19:00  New York Worlds Fair NY

In [25]:
movies=pd.read_csv('http://bit.ly/imdbratings')  # Read the IMDb ratings CSV file into a pandas DataFrame

In [26]:
movies.head()  # Display the first few rows of the IMDb ratings DataFrame

star_rating                     title content_rating   genre  duration  \
0          9.3  The Shawshank Redemption              R   Crime       142   
1          9.2             The Godfather              R   Crime       175   
2          9.1    The Godfather: Part II              R   Crime       200   
3          9.0           The Dark Knight          PG-13  Action       152   
4          8.9              Pulp Fiction              R   Crime       154   

                                         actors_list  
0  [u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt...  
1    [u'Marlon Brando', u'Al Pacino', u'James Caan']  
2  [u'Al Pacino', u'Robert De Niro', u'Robert Duv...  
3  [u'Christian Bale', u'Heath Ledger', u'Aaron E...  
4  [u'John Travolta', u'Uma Thurman', u'Samuel L....

In [28]:
movies.title.sort_values(ascending=False)  # Sort the 'title' column in the IMDb ratings DataFrame by alphabet 

864                    [Rec]
526                     Zulu
615               Zombieland
677                   Zodiac
955         Zero Dark Thirty
               ...          
110    2001: A Space Odyssey
698                127 Hours
201         12 Years a Slave
5               12 Angry Men
542     (500) Days of Summer
Name: title, Length: 979, dtype: object

In [29]:
movies.sort_values('title')


star_rating                  title content_rating      genre  duration  \
542          7.8   (500) Days of Summer          PG-13     Comedy        95   
5            8.9           12 Angry Men      NOT RATED      Drama        96   
201          8.1       12 Years a Slave              R  Biography       134   
698          7.6              127 Hours              R  Adventure        94   
110          8.3  2001: A Space Odyssey              G    Mystery       160   
..           ...                    ...            ...        ...       ...   
955          7.4       Zero Dark Thirty              R      Drama       157   
677          7.7                 Zodiac              R      Crime       157   
615          7.7             Zombieland              R     Comedy        88   
526          7.8                   Zulu        UNRATED      Drama       138   
864          7.5                  [Rec]              R     Horror        78   

                                           actors_list  
542  [u'Zooey Deschanel', u'Joseph Gordon-Levitt', ...  
5    [u'Henry Fonda', u'Lee J. Cobb', u'Martin Bals...  
201  [u'Chiwetel Ejiofor', u'Michael Kenneth Willia...  
698  [u'James Franco', u'Amber Tamblyn', u'Kate Mara']  
110  [u'Keir Dullea', u'Gary Lockwood', u'William S...  
..                                                 ...  
955  [u'Jessica Chastain', u'Joel Edgerton', u'Chri...  
677  [u'Jake Gyllenhaal', u'Robert Downey Jr.', u'M...  
615  [u'Jesse Eisenberg', u'Emma Stone', u'Woody Ha...  
526  [u'Stanley Baker', u'Jack Hawkins', u'Ulla Jac...  
864  [u'Manuela Velasco', u'Ferran Terraza', u'Jorg...  

[979 rows x 6 columns]

In [31]:
movies.sort_values(['content_rating','duration' ])


star_rating                               title content_rating  \
713          7.6                     The Jungle Book       APPROVED   
513          7.8      Invasion of the Body Snatchers       APPROVED   
272          8.1                         The Killing       APPROVED   
703          7.6                             Dracula       APPROVED   
612          7.7                  A Hard Day's Night       APPROVED   
..           ...                                 ...            ...   
387          8.0                     Midnight Cowboy              X   
86           8.4                  A Clockwork Orange              X   
187          8.2  Butch Cassidy and the Sundance Kid            NaN   
936          7.4                           True Grit            NaN   
649          7.7                   Where Eagles Dare            NaN   

         genre  duration                                        actors_list  
713  Animation        78  [u'Phil Harris', u'Sebastian Cabot', u'Louis P...  
513     Horror        80  [u'Kevin McCarthy', u'Dana Wynter', u'Larry Ga...  
272      Crime        85  [u'Sterling Hayden', u'Coleen Gray', u'Vince E...  
703     Horror        85  [u'Bela Lugosi', u'Helen Chandler', u'David Ma...  
612     Comedy        87  [u'John Lennon', u'Paul McCartney', u'George H...  
..         ...       ...                                                ...  
387      Drama       113  [u'Dustin Hoffman', u'Jon Voight', u'Sylvia Mi...  
86       Crime       136  [u'Malcolm McDowell', u'Patrick Magee', u'Mich...  
187  Biography       110  [u'Paul Newman', u'Robert Redford', u'Katharin...  
936  Adventure       128    [u'John Wayne', u'Kim Darby', u'Glen Campbell']  
649     Action       158  [u'Richard Burton', u'Clint Eastwood', u'Mary ...  

[979 rows x 6 columns]

In [33]:
bol = []
for length in movies.duration:
    if length > 200:
        bol.append(True)
    else:
        bol.append(False)

bol [0:10]  # Display the first 10 boolean values indicating whether the movie duration is greater than 200 minutes

[False, False, False, False, False, False, False, True, False, False]

In [34]:
movies.loc[movies.duration > 200, 'genre']  # Display the titles of movies with a duration greater than 200 minutes

7      Adventure
17         Drama
78         Crime
85     Adventure
142    Adventure
157        Drama
204    Adventure
445    Adventure
476        Drama
630    Biography
767       Action
Name: genre, dtype: object

In [35]:
movies.loc[(movies.duration > 200) & (movies.genre == "Drama")]  # Display the titles of movies with a duration greater than 200 minutes

star_rating               title content_rating  genre  duration  \
17           8.7       Seven Samurai        UNRATED  Drama       207   
157          8.2  Gone with the Wind              G  Drama       238   
476          7.8              Hamlet          PG-13  Drama       242   

                                           actors_list  
17   [u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K...  
157  [u'Clark Gable', u'Vivien Leigh', u'Thomas Mit...  
476  [u'Kenneth Branagh', u'Julie Christie', u'Dere...

In [37]:
import numpy as np  # Import the NumPy library for numerical operations.
import pandas as pd  #  Import the pandas library for data manipulation and analysis.
import seaborn as sns  # Import the seaborn library for data visualization.
import matplotlib.pyplot as plt # Import the matplotlib library for creating static, interactive, and animated visualizations.
import warnings  # Import the warnings library to handle warning messages.
warnings.filterwarnings("ignore")  # Ignore warning messages to keep the output clean.


In [39]:
df = pd.read_csv('train.csv')
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [41]:
df.drop(['PassengerId','Name','Ticket'] , axis=1, inplace=True)  # Drop the specified columns from the DataFrame
df.head()  # Display the first few rows of the DataFrame after dropping the specified columns

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [42]:
df.dtypes  # Display the data types of each column in the DataFrame

Survived      int64
Pclass        int64
Sex          object
Age         float64
SibSp         int64
Parch         int64
Fare        float64
Cabin        object
Embarked     object
dtype: object

In [43]:
dtypes = df.dtypes  # Store the data types of each column in a variable
n_uniq = df.nunique()  # Count the number of unique values in each column
n_uniq  # Display the number of unique values in each column


Survived      2
Pclass        3
Sex           2
Age          88
SibSp         7
Parch         7
Fare        248
Cabin       147
Embarked      3
dtype: int64

In [45]:
dtypes = df.dtypes  # Store the data types of each column in a variable
n_uniq = df.nunique()  # Count the number of unique values in each column
pd.DataFrame({'dtypes': dtypes, 'n_uniq': n_uniq}) .T  # Create a new DataFrame with the data types and number of unique values of each column

Survived Pclass     Sex      Age  SibSp  Parch     Fare   Cabin  \
dtypes    int64  int64  object  float64  int64  int64  float64  object   
n_uniq        2      3       2       88      7      7      248     147   

       Embarked  
dtypes   object  
n_uniq        3

In [46]:
def dtypes_and_unique(df):
    dtypes = df.dtypes  # Store the data types of each column in a variable
    n_uniq = df.nunique()  # Count the number of unique values in each column
    
    return pd.DataFrame({'dtypes': dtypes, 'n_uniq': n_uniq}) .T  # Create a new DataFrame with the data types and number of unique values of each column

In [47]:
dtypes_and_unique(df)  # Call the function to get the data types and number of unique values of each column in the DataFrame

Survived Pclass     Sex      Age  SibSp  Parch     Fare   Cabin  \
dtypes    int64  int64  object  float64  int64  int64  float64  object   
n_uniq        2      3       2       88      7      7      248     147   

       Embarked  
dtypes   object  
n_uniq        3

In [49]:
from preprocess import dtypes_and_unique  # Import the dtypes_and_unique function from the preprocessing module

dtypes_and_unique(df)  # Call the function to get the data types and number of unique values of each column in the DataFrame

Survived Pclass     Sex      Age  SibSp  Parch     Fare   Cabin  \
dtypes    int64  int64  object  float64  int64  int64  float64  object   
n_uniq        2      3       2       88      7      7      248     147   

       Embarked  
dtypes   object  
n_uniq        3

In [51]:
cols = ['Survived', 'Pclass', 'Sex', 'SibSp','Parch','Embarked' ]   # List of columns to be converted to categorical data type
df[cols] = df[cols].astype('category')  # Convert the specified columns to categorical data type
pd.DataFrame(df.dtypes) .T # Display the data types of all columns in the DataFrame

Survived    Pclass       Sex      Age     SibSp     Parch     Fare   Cabin  \
0  category  category  category  float64  category  category  float64  object   

   Embarked  
0  category

In [52]:
null = df. isnull()
null

Survived  Pclass    Sex    Age  SibSp  Parch   Fare  Cabin  Embarked
0       False   False  False  False  False  False  False   True     False
1       False   False  False  False  False  False  False  False     False
2       False   False  False  False  False  False  False   True     False
3       False   False  False  False  False  False  False  False     False
4       False   False  False  False  False  False  False   True     False
..        ...     ...    ...    ...    ...    ...    ...    ...       ...
886     False   False  False  False  False  False  False   True     False
887     False   False  False  False  False  False  False  False     False
888     False   False  False   True  False  False  False   True     False
889     False   False  False  False  False  False  False  False     False
890     False   False  False  False  False  False  False   True     False

[891 rows x 9 columns]

In [56]:
null = df. isnull() 
null.sum()   # Count the number of null values in each column of the DataFrame

Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [58]:
null = df. isnull() .sum()  # Count the number of null values in each column of the DataFrame
ratio = (null/ df.shape[0]) *100
pd.DataFrame({'null': null, 'ratio': ratio}) .T # Create a new DataFrame with the count and ratio of null values in each column

Survived  Pclass  Sex        Age  SibSp  Parch  Fare       Cabin  \
null        0.0     0.0  0.0  177.00000    0.0    0.0   0.0  687.000000   
ratio       0.0     0.0  0.0   19.86532    0.0    0.0   0.0   77.104377   

       Embarked  
null   2.000000  
ratio  0.224467