In [2]:
class STUDENT:
    def __init__(self):
        self.student_name = "Mohamed gamal"
        self.Student_age = 35
        self.student_grade = 3.99
        self.student_gender = "male"

    def student_info(self):
        print(f"My name is : {self.student_name}")
        print(f"My age is: {self.Student_age}") 
        print(f"My grade : {self.student_grade}")
        print(f"My gender : {self.student_gender}")

s1 = STUDENT()
s1.student_info()

My name is : Mohamed gamal
My age is: 35
My grade : 3.99
My gender : male


In [ ]:

#class Calculator take two numbers and perform addition and subtraction
# and print the results
class Calculator:
    def __init__(self, num1, num2):
        self.num1 = num1
        self.num2 = num2
    def add(self):
        return self.num1 + self.num2
    def subtract(self):
        return self.num1 - self.num2



num1 = int(input("Enter first number: "))   # Input first numbers from the user 
num2 = int(input("Enter second number: "))  # Input second numbers from the user 

c1 = Calculator(num1, num2)    # inherits the class Calculator
c1.add()                        # performs addition
c2 = Calculator(num1, num2)
c2.subtract()
print (f"Addition of {num1} and {num2} is: {c1.add()}")
print (f"Subtraction of {num1} and {num2} is: {c2.subtract()}")

Addition of 10 and 5 is: 15
Subtraction of 10 and 5 is: 5


In [1]:
from abc import ABC, abstractmethod

class Animal (ABC):
    @abstractmethod
    def move(self):
        pass

class Bird(Animal):
    def move(self):
        print("I can fly")

class Cat(Animal):
    def move(self):
        print("I can run")

a = Bird()
a.move()

I can fly


In [2]:
class A():
    def do_this(self):
        print("A is doing this")

class B(A):
    pass

class C():
    def do_this(self):
        print("C is doing this")

class D(B, C):
    pass

d = D()
x = d.do_this()

A is doing this


In [6]:
import random
class password_generator:
    def __init__(self, length):
        self.length = length

    def generate(self):
        characters = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*()"
        password = ""

        for _ in range(self.length):
            password += random.choice(characters)
        return password
    
if __name__ == "__main__":
    p1 = password_generator(10)  # Create an instance with desired length
    p1.generate()  # Generate the password
    print(f"Generated password: {p1.generate()}")  # Print the generated password





Generated password: vq(DP4WXdp


In [7]:
class WordFrequencyCounter:

    def __init__(self, words):
    
        self.words = words

    def count_frequencies(self):
    
        freq_dict = {}
        for word in self.words:
            if word in freq_dict:
                freq_dict[word] += 1
            else:
                freq_dict[word] = 1
        return freq_dict
if __name__ == "__main__":
    
    words = ["Welcome", "Ali", "Hi", "Ali", "No", "Hi", "No", "Ali", "No", "Ali"]
    
    counter = WordFrequencyCounter(words)
    result = counter.count_frequencies()

    for word, count in result.items():
        print(f"{word}: {count}")

Welcome: 1
Ali: 4
Hi: 2
No: 3


In [ ]:
def count_word_frequencies(words):
    freq_dict = {}
    for word in words:
        if word in freq_dict:
            freq_dict[word] += 1
        else:
            freq_dict[word] = 1
    return freq_dict

words = ["Welcome", "Ali", "Hi", "Ali", "No", "Hi", "No", "Ali", "No", "Ali"]
unique_words = set(words)
counts = {word: words.count(word) for word in unique_words}
for word in unique_words:
    print(f"{word}: {counts[word]}")




In [ ]:

def count_word_frequencies(words):

    freq_dict = {}
    for word in words:
        freq_dict[word] = freq_dict.get(word, 0) + 1
    return freq_dict

words = ["Welcome", "Ali", "Hi", "Ali", "No", "Hi", "No", "Ali", "No", "Ali"]

counts = count_word_frequencies(words)

for word in sorted(counts):
    print(f"{word}: {counts[word]}")

In [ ]:
class WordFrequencies:
    def __init__(self, words):
        self.words = words

    def count_word_frequencies(self):
        freq_dict = {}
        for word in self.words:
            freq_dict[word] = freq_dict.get(word, 0) + 1
        return freq_dict

    def display_frequencies(self):
        counts = self.count_word_frequencies()
        for word in sorted(counts):
            print(f"{word}: {counts[word]}")

if __name__ == "__main__":
    words = ["Welcome", "Ali", "Hi", "Ali", "No", "Hi", "No", "Ali", "No", "Ali"]
    wf = WordFrequencies(words)
    wf.display_frequencies()


In [ ]:
import random

# Predefined responses
responses = {
    "hello": ["Hello!", "Hi there!", "Greetings!"],
    "how are you": ["I'm doing well, thank you!", "I'm fine, how about you?"],
    "goodbye": ["Goodbye!", "See you later!", "Farewell!"],
    "default": ["I'm sorry, I didn't understand.", "Could you please rephrase that?"]
}

# Function to get a response based on user input
def get_response(user_input):
    for key in responses:
        if key in user_input:
            return random.choice(responses[key])
    
    return random.choice(responses["default"])

# Chatbot function
def chatbot():
    print("Chatbot: Hi! How can I assist you today?")
    
    while True:
        user_input = input("User: ").lower()
        response = get_response(user_input)
        print("Chatbot:", response)
        
        if user_input == "goodbye":
            break

# Run the chatbot
chatbot()

In [12]:
import random

class ChatBot:
    def __init__(self):
        self.responses = {
            "hello": ["Hello!", "Hi there!", "Greetings!"],
            "how are you": ["I'm good, thanks!", "Doing well, and you?"],
            "goodbye": ["Goodbye!", "See you!", "Take care!"],
            "default": ["I didn't get that.", "Could you repeat it?"]
        }

    def get_response(self, user_input):
        user_input = user_input.lower()
        for key in self.responses:
            if key in user_input:
                return random.choice(self.responses[key])
        return random.choice(self.responses["default"])

    def start(self):
        print("Chatbot: Hello! Type 'goodbye' to exit.")
        while True:
            user_input = input("You: ")
            response = self.get_response(user_input)
            print("Chatbot:", response)
            if "goodbye" in user_input.lower():
                break


bot = ChatBot()
bot.start()


Chatbot: Hello! Type 'goodbye' to exit.
Chatbot: Hi there!
Chatbot: Could you repeat it?
Chatbot: I'm good, thanks!
Chatbot: Could you repeat it?
Chatbot: Goodbye!


In [3]:
import numpy as np

# Example usage of numpy
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(v1)
print(v2)


[1 2 3]
[4 5 6]


In [ ]:
list_1 = [1, 2, 3] 
print(type(list_1)) # check type of list_1
# Convert list_1 to a numpy array
x = np.array(list_1) 
print(type(x))

<class 'list'>
<class 'numpy.ndarray'>


In [6]:
v1 = np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
w= v1 * v2  # Add two numpy arrays
print(w)  # Print the result of the addition


[ 4 10 18]


In [1]:
import numpy as np

In [7]:
s= np.array(5)  # Create a numpy array with a single element
print (type(s))  # Check the type of the numpy array
print("D", s.ndim)  # Print the number of dimensions
print(s)  # Print the numpy array

<class 'numpy.ndarray'>
D 0
5


In [9]:
v= np.array([1, 2, 3])
print(type(v))  # Check the type of the numpy array
print(v.shape)  # Print the shape of the numpy array
v

<class 'numpy.ndarray'>
(3,)


array([1, 2, 3])

In [11]:
m= np.array([[1, 2, 3],
            [4, 5, 6]
            ])
print(type(m))  # Check the type of the numpy array
print(m.ndim , "D")  # Print the number of dimensions
print(m.shape)  # Print the shape of the numpy array
print(m)  # Print the numpy array

<class 'numpy.ndarray'>
2 D
(2, 3)
[[1 2 3]
 [4 5 6]]


In [12]:
vec_1 = np.array([1, 2, 3, 4 ,5 , 6])  
matrix_1 = vec_1.reshape(3,2)  # Reshape the vector into a 2x3 matrix
print(matrix_1)  # Print the reshaped matrix
print(type(matrix_1))  # Check the type of the reshaped matrix

[[1 2]
 [3 4]
 [5 6]]
<class 'numpy.ndarray'>


In [17]:
vec_2 = np.array([1, 2, 3, 4 ,5 ])
matrix_3 = vec_2.reshape(vec_2.shape[0],1)  
print(matrix_3)  

[[1]
 [2]
 [3]
 [4]
 [5]]


In [18]:
vec_2 = np.array([1, 2, 3, 4 ,5 ])
#matrix_3 = vec_2.reshape(vec_2.shape[0],1)  
matrix_4 = vec_2[:, None]  # Reshape the vector into a column vector
print(matrix_4) 

[[1]
 [2]
 [3]
 [4]
 [5]]


In [19]:
m_1 = np.array([[1, 2, 3],
                [4, 5, 6],
                [7,8,9]
                ])

print(m_1.dtype)  # Check the type of the numpy array

int64


In [20]:
m_1 = np.array([[1, True, 3],
                [4, 5, 6],
                [7,8,9]
                ])

print(m_1.dtype)  # Check the type of the numpy array

int64


In [27]:
class student:
    def __init__(self, name):
        self.name = name

s = student("Mohamed Gamal")
m_1 = np.array([[1, True, s.name],
                [4, 5, 6],
                [7,8,9]
                ])

print(m_1.dtype) 
print(m_1)  # Print the numpy array with mixed data types


<U21
[['1' 'True' 'Mohamed Gamal']
 ['4' '5' '6']
 ['7' '8' '9']]


In [ ]:
m = np.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [0,0,0]
        ])  # indexing example [1 ,2 , 3] = index 0 

m[1,2]

np.int64(6)

In [31]:
m = np.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [0,0,0]
        ])  # indexing example [1 ,2 , 3] = index 0 

m[1,-2]

np.int64(5)

In [33]:
v_3 = np.array([3,2,5,1,2,3,0])
v_3[2:6]  # Slicing the array to get elements from index 2 to 4

array([5, 1, 2, 3])

In [34]:
m = np.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [0,0,0]
        ])

m[1:3 , 0:2]  # Slicing the array to get rows 1 to 2 and columns 0 to 1

array([[4, 5],
       [7, 8]])

In [35]:
m = np.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [0,0,0]
        ])

m[-3:-1 , -3:-1]  # Slicing the array to get rows 1 to 2 and columns 0 to 1

array([[4, 5],
       [7, 8]])

In [36]:
m = np.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [0,0,0]
        ])

mat_t = m.T  # Transpose the matrix
print(mat_t)  # Print the transposed matrix

[[1 4 7 0]
 [2 5 8 0]
 [3 6 9 0]]


In [38]:
mat = np.zeros((3, 4))  # Create a 2x3 matrix filled with zeros
mat

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
mat = np.ones((3, 4))  # Create a 2x3 matrix filled with zeros
mat

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
mat = np.full((3, 4), 5)  # Create a 3*4 matrix filled with fives
print(mat)  # Print the matrix filled with fives

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [44]:
mat = np.empty((3, 4))  # Create an empty matrix with shape 3x4
print(mat)  # Print the empty matrix

[[2.5e-323 2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323 2.5e-323]]


In [47]:
angles = np.arange(0,361,30)  # Create a numpy array with angles
print(angles)  # Print the numpy array with angles

[  0  30  60  90 120 150 180 210 240 270 300 330 360]


In [51]:
vec = np.linspace(0, 10, num = 10)  # Create a numpy array with evenly spaced values
print(vec)  # Print the numpy array with evenly spaced values

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]


In [53]:
iden = np. identity(3,)      # Create a 3x3 identity matrix
print(iden)  # Print the identity matrix

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [57]:
vec = np.linspace(0, 10, num = 25)  # Create a numpy array with evenly spaced values
mat = vec.reshape(5, 5)  # Reshape the vector into a 5x5 matrix
print(mat)  # Print the numpy array with evenly spaced values

[[ 0.          0.41666667  0.83333333  1.25        1.66666667]
 [ 2.08333333  2.5         2.91666667  3.33333333  3.75      ]
 [ 4.16666667  4.58333333  5.          5.41666667  5.83333333]
 [ 6.25        6.66666667  7.08333333  7.5         7.91666667]
 [ 8.33333333  8.75        9.16666667  9.58333333 10.        ]]
