In [3]:
import tensorflow as tf

In [4]:
print ("TensorFlow version:", tf.__version__)

TensorFlow version: 2.20.0


In [5]:
x = tf.constant([[5 ,2], [1 , 3]])
print (x)
type(x)

tf.Tensor(
[[5 2]
 [1 3]], shape=(2, 2), dtype=int32)


tensorflow.python.framework.ops.EagerTensor

In [7]:
print(tf.ones(shape = (2,1)))
print(tf.zeros(shape = (2,1)))

tf.Tensor(
[[1.]
 [1.]], shape=(2, 1), dtype=float32)
tf.Tensor(
[[0.]
 [0.]], shape=(2, 1), dtype=float32)


In [11]:
intial_w = tf.random.normal(shape=(2,2))
a = tf.Variable(intial_w)
print(a)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[ 1.1474302 , -0.47670445],
       [ 1.0374777 ,  0.25676173]], dtype=float32)>
